const Components = {
	Accordion: 'accordion',
	Alert: 'alert',
	Avatar: 'avatar',
	Badge: 'badge',
	Button: 'button',
	ButtonGroup: 'alert',
	Card: 'card',
	Col: 'col',
	Container: 'container',
	Dropdown: 'dropdown',
	IconButton: 'iconButton',
	List: 'list',
	Modal: 'modal',
	Pagination: 'pagination',
	Progress: 'progress',
	Row: 'row',
	Spinner: 'spinner',
	Table: 'table',
	Tab: 'tab',
	Typography: 'typography',
}
export const prefix = 'ai'
export const ComponentsArray = [
	'ati-message-alert',
	'accordion',
	'alert',
	'avatar',
	'badge',
	'btn',
	'alert',
	'card',
	'col',
	'container',
	'dropdown',
	'list',
	'modal',
	'pagination',
	'progress',
	'row',
	'spinner',
	'table',
	'tab',
	'tooltip',
	'typography'] as const;

export default Components
